### PR TITLE
sequential graph display bug fix

### PR DESCRIPTION
**Pull request by allenzhuaz**
This PR is to fix the bug of displaying the same (last) graph in multiple tabs.

### CODE REVIEW

**Comment by allenzhuaz** [comment]
@nanxstats For the multiple-graph tab, it would be more desired if we can always display the last tabset instead the firs tabset. Seemingly `tabsetPanel()` does not support this, any idea?

**Comment by XDeng0921** [comment]
@allenzhuaz can you please help me to understand this task? Are we going to display the final graph instead of displaying iterative steps as we did before?

**Comment by XDeng0921** [comment]
@allenzhuaz sorry it seems I inadvertently deleted your PR? can you please help me to understand this task? Are we going to display the final graph instead of displaying iterative steps as we did before?

**Comment by allenzhuaz** [comment]
> @allenzhuaz sorry it seems I inadvertently deleted your PR? can you please help me to understand this task? Are we going to display the final graph instead of displaying iterative steps as we did before?
> 
No, this PR still to display the iterative graphs as multiple tabs.  the merged PR #80 did not show iterative graphs correctly, so I opened this PR to fix. 

> As discussed last time, I incorporated the comments and debugged some outputs used for observe(). I will push for your review, and we can further discuss this PR?

Sure, please feel free to push, though this PR I considered using `observe`...I will also try to apply @nanxstats latest example in #78 , to move the display focus to last tab of the iterative graphs

**Comment by allenzhuaz** [comment]
applied the commits to #82

**Pull request closed without merging**
